#BaseURL = "https://ringo.de-smet.name/"
BaseURL = "http://static.site.ringo.de-smet.name.s3-website-eu-west-1.amazonaws.com/"
LanguageCode = "en-uk"
Title = "Ringo De Smet"
Theme="casper"
#DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2015"

[params]
  description = "Code of Ringo"
  cover = "images/cover_polenord.jpg"
  author = "Ringo De Smet"
  authorlocation = "Lokeren, Belgium"
  authorwebsite = "https://ringo.de-smet.name"
  #bio= "my bio"
  #logo = "images/logo.png"
  #googleAnalyticsUserID = ""
  githubName = "ringods"
  twitterName = "ringods"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[permalinks]
  post = "/:year/:month/:title/"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Github"
  weight = 100
  pre = "<h3>Follow me</h3>"
  url = "https://github.com/ringods"

[[menu.main]]
  name = "Twitter"
  weight = 101
  url = "https://twitter.com/ringods"
